# syntax=docker/dockerfile:1

FROM golang:1.23.2 as builder

WORKDIR /todo-list

COPY go.mod go.sum ./

COPY vendor/ ./vendor

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o todo-list ./cmd

FROM alpine:latest


WORKDIR /root/

COPY --from=builder /todo-list/cmd .
COPY --from=builder /todo-list/config/ ./config/ 

EXPOSE 4853

CMD ./todo
