version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=heli_tech_backend
      - SQS_ENDPOINT=http://localstack:4566
    depends_on:
      - database
      - localstack

  database:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heli_tech_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack main port
      - "4576:4576"  # SQS service
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1

volumes:
  postgres-data:
