version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heli_tech_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # LocalStack service (SQS, S3, etc.)
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510:4510"  # LocalStack UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack/data

  # Your Go application
  app:
    build: .
    container_name: todo-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: heli_tech_backend
      SQS_ENDPOINT: http://localstack:4566
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - localstack
    networks:
      - todo-network

volumes:
  postgres-data:
  localstack-data:

networks:
  todo-network:
    driver: bridge
